### ISSUE TITLE
Emphasize Jira Bugs that are in progress

### ISSUE THREAD

**Issue by wThomas84** [as-ideas/ideas-dash#12]
As developer using the dash I want to be able to see which JIRA Bugs are currently in progress in order to be able to decide faster on which task I should work next.

**Comment by CanardSauvage** [comment]
This is difficult, as "in progress" depends on the jira-configuration.

**Comment by gaffa** [comment]
this has been solved, hasnt it?

**Comment by CanardSauvage** [comment]
Yes ;)
