### ISSUE TITLE
cpu usage enormous

### ISSUE THREAD

**Issue by gaffa** [as-ideas/ideas-dash#19]
i guess there is a bug somewhere in the client code as my cooler began spinning real fast and the tab-task used 50% of my cpu (for comparison: facebook is at 5%). even battery went from  3h+ to 1h.

**Comment by CanardSauvage** [comment]
It is the glow effect for "running" Checks. I will replace the css with something more simple.

**Comment by gaffa** [comment]
https://github.com/as-ideas/ideas-dash/pull/21
