### ISSUE TITLE
Wrong time zone

### ISSUE THREAD

**Issue by milek** [as-ideas/ideas-dash#20]
Dashboard displays wrong time zone (UTC) without informing it.
In https://github.com/as-ideas/ideas-dash/blob/master/dash-core/src/main/java/de/axelspringer/ideas/tools/dash/presentation/UiInfoService.java#L56 I would suggest to use ZonedDateTime() with format pattern that can be read by Angular (here I can't help, since I don't know Angular at all)

**Comment by gaffa** [comment]
https://github.com/as-ideas/ideas-dash/pull/22

**Comment by gaffa** [comment]
fix approved by reporter. closing.
