### ISSUE TITLE
example-app

### ISSUE THREAD

**Issue by gaffa** [as-ideas/ideas-dash#6]
we should include a module with an example-app to make development more configurable (currently ideas-dash has to be installed with maven and used in a consumer-dash to test changes).

maybe that example-app also could mock some services (jenkins aso) and be used for more automated tests...

**Comment by CanardSauvage** [comment]
I think I can include an example app this weekend and add some cucumber tests.

**Comment by gaffa** [comment]
fixed wo tests or any further functionality
